### ISSUE TITLE
Local sync is broken

### ISSUE THREAD

**Issue by penberg** [libsql/libsql#374]
When I run the local sync example, I get the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Misuse("No replicator available. Use Database::with_replicator() to enable replication")', core/examples/local_sync.rs:24:56
```

**Comment by penberg** [comment]
Local sync is unfortunately still broken:

```
Applying snapshot to local database: /tmp/airgap-demo/client/5e090ed2-3737-401c-9cc1-ad46ec856b34-0-1.snap

Applying snapshot to local database: /tmp/airgap-demo/client/5e090ed2-3737-401c-9cc1-ad46ec856b34-2-3.snap

2023-09-13T04:20:57.513907Z  WARN libsql_replication: Snapshot header frame number 2 does not match post-commit frame number 1
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionFailed("Snapshot header frame number 2 does not match post-commit frame number 1")', core/examples/local_sync.rs:27:76
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(10), ...)', core/examples/local_sync.rs:30:14
```
